############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb secret creation
# Purpose: creates b64-encoded secrets for MariaDB master/slave
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: exercise-02
  labels:
    app: wordpress
    tier: database
    stage: production
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: Yml0bmFtaV93b3JkcHJlc3NfcGFzcw==
  MARIADB_PASSWORD: cm9vdF93cA==
  MARIADB_REPLICATION_PASSWORD: cmVwbGljYXRpb25fcGFzc3dk