---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: exercise-02
  labels:
    app: mariadb
data:
  MARIADB_DATABASE: bitnami_wordpress
  MARIADB_USER: bn_wordpress
  MARIADB_REPLICATION_USER: replicator
  
