apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-slave
  namespace: exercise-02
  labels:
    app: mariadb
    tier: backend
    role: slave
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
      tier: backend
      role: slave
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
        role: slave
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        ports:
          - name: mysql
            containerPort: 3306
        env:
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-dbname
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-password
          - name: MARIADB_REPLICATION_MODE
            value: slave
          - name: MARIADB_MASTER_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-config
                key: mariadb-host
          - name: MARIADB_MASTER_ROOT_USER
            value: "root"
          - name: MARIADB_MASTER_PORT_NUMBER
            value: "3306"
          - name: MARIADB_MASTER_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: root-password
          - name: MARIADB_REPLICATION_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: repl-user
          - name: MARIADB_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: repl-password
        # livenessProbe:
        #   exec:
        #     command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
