apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-02
  labels:
    app: wordpress
    tier: frontend
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200
  ports:
    - name: frontend
      port: 8080
      targetPort: http-server
  selector:
    app: wordpress
    tier: frontend
