apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise01
spec:
  replicas: 1
  template:
    metadata: 
        labels:
          app: wordpress
          track: canary
    spec:
      selector:
          app: wordpress
          tier: frontend
      type: LoadBalancer
      containers:
      - image: bitnami/wordpress:4.9.4
        name: wordpress
        env: 
        - name: WORDPRESS_USERNAME
          value: "user"
        - name: WORDPRESS_PASSWORD
          value: "password"		
        - name: WORDPRESS_EMAIL
          value: "user@example.com"	
        - name: WORDPRESS_FIRST_NAME
          value: "FirstName"
        - name: WORDPRESS_LAST_NAME
           value: "LastName"
        - name: WORDPRESS_BLOG_NAME
          value: "User's blog"	
          ports: 
                   - port: 80
	livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m