############################ # ############################
## Bitnami K8S training
## session01/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress service
# Purpose: exposes a "wordpress" NodePort service through the kubedns
############################ # ############################
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
    tier: frontend
    stage: production
spec:
  selector:
    app: wordpress
    tier: frontend
    # stage is  not defined, so that we can select both production and canary
  ports:
  - name: http-svc-port
    protocol: TCP
    port: 80
    targetPort: http-port
    nodePort: 30080
  - name: https-svc-port
    protocol: TCP
    port: 443
    targetPort: https-port
    nodePort: 30443
  type: NodePort
  # type: LoadBalancer
  sessionAffinity: ClientIP