############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress service
# Purpose: exposes a "wordpress" NodePort service through the kubedns
############################ # ############################
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: s02-exercise-01
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
  - name: http-svc-port
    protocol: TCP
    port: 80
    targetPort: http-port
    nodePort: 31080
  - name: https-svc-port
    protocol: TCP
    port: 443
    targetPort: https-port
    nodePort: 31443
  type: NodePort