apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-canary-deployment
  namespace: exercise-01
  labels:
    app: wordpress
    tier: frontend
    track: canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        track: canary
    spec:
      containers:
      - image: bitnami/wordpress:4.9.8
        livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 30
            httpGet:
              path: /
              port: 80
        readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              path: /
              port: 80
        name: wordpress
        ports:
        - name: wordpress
          containerPort: 80
        env:
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: mariadb-database-password
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: mariadb-hostname
          - name: WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: username-wp
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: password-wp
          - name: WORDPRESS_EMAIL
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: email-wp
        envFrom:
          - configMapRef:
              name: wp-configmap
