apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: exercise-01
  labels:
    app: mariadb
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      tier: backend
  template:
    metadata:
      labels: 
        app: mariadb
        tier: backend
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
        ports:
          - name: mariadb-server
            containerPort: 3306