############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress secret creation
# Purpose: creates b64-encoded secrets for Wordpress
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: exercise-02
  labels:
    app: wordpress
    tier: frontend
    stage: production
type: Opaque
data:
  WORDPRESS_DATABASE_PASSWORD: cm9vdF93cA==
  WORDPRESS_PASSWORD: YW50b25pb193cA== #"antonio_wp"