apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:4.9.7
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: database.name
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: database.user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database.password
        - name: WORDPRESS_EMAIL
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: email
        - name: WORDPRESS_FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: first.name
        - name: WORDPRESS_LAST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: last.name
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: blog.name

        ports:
        - name: wordpress
          containerPort: 80
