---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
data:
  database_password: SWV4aWExdVY=
  database_name: bitnami_wordpress
  database_user: bn_wordpress
  wordpress_email: japi@kolokium.com
