############################ # ############################
## Bitnami K8S training
## session01/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb secret creation
# Purpose: creates b64-encoded secrets for MariaDB
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: exercise-01
  labels:
    app: wordpress
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: Yml0bmFtaV93b3JkcHJlc3NfcGFzcw==
  MARIADB_PASSWORD: cm9vdF93cA==
  MARIADB_USER: azhzX3dvcmRwcmVzc191c2Vy # k8s_wordpress_user